// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs types_hid_windows.go

package hid

type (
	_GUID struct {
		Data1 uint32
		Data2 uint16
		Data3 uint16
		Data4 [8]uint8
	}
	_TCHAR                    int8
	_SP_DEVICE_INTERFACE_DATA struct {
		CbSize             uint32
		InterfaceClassGuid _GUID
		Flags              uint32
		Reserved           uint64
	}
	_SP_DEVINFO_DATA struct {
		CbSize    uint32
		ClassGuid _GUID
		DevInst   uint32
		Reserved  uint64
	}
	_SP_DEVICE_INTERFACE_DETAIL_DATA_W struct {
		CbSize     uint32
		DevicePath [1]uint16
		Pad_cgo_0  [2]byte
	}
	_HIDD_ATTRIBUTES struct {
		Size          uint32
		VendorID      uint16
		ProductID     uint16
		VersionNumber uint16
		Pad_cgo_0     [2]byte
	}
	_PHIDP_PREPARSED_DATA uintptr
	_HIDP_CAPS            struct {
		Usage                     uint16
		UsagePage                 uint16
		InputReportByteLength     uint16
		OutputReportByteLength    uint16
		FeatureReportByteLength   uint16
		Reserved                  [17]uint16
		NumberLinkCollectionNodes uint16
		NumberInputButtonCaps     uint16
		NumberInputValueCaps      uint16
		NumberInputDataIndices    uint16
		NumberOutputButtonCaps    uint16
		NumberOutputValueCaps     uint16
		NumberOutputDataIndices   uint16
		NumberFeatureButtonCaps   uint16
		NumberFeatureValueCaps    uint16
		NumberFeatureDataIndices  uint16
	}
)
